// Use the client generated by Prisma. This produces a local module
// with proper type declarations (`PrismaClient` etc.) that avoids
// any issues with the top‑level package's broken `index.d.ts`.
import { PrismaClient } from "./generated/prisma/client";
// Prisma 7 requires specifying an adapter or accelerateUrl when using the
// new client engine. We simply use the PostgreSQL adapter to keep the
// default binary behaviour and point it at our DATABASE_URL.
import { PrismaPg } from "@prisma/adapter-pg";

export const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
});
